// Generated by https://quicktype.io

namespace Sunrise.Integrations.Vk.Types
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
[System.Diagnostics.DebuggerStepThrough]
    public partial class UpdateResult
    {
        [JsonProperty("failed")]
        public int ErrorStatus {get; set;} = 0;

        [JsonProperty("ts")]
        public string Ts { get; set; }

        [JsonProperty("updates")]
        public Update[] Updates { get; set; }
    }

    public partial class Update
    {
        [JsonProperty("group_id")]
        public long GroupId { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("event_id")]
        public string EventId { get; set; }

        [JsonProperty("v")]
        public string V { get; set; }

        [JsonProperty("object")]
        public Object Object { get; set; }
    }

    public partial class Object
    {
        [JsonProperty("message")]
        public Message Message { get; set; }

        [JsonProperty("client_info")]
        public ClientInfo ClientInfo { get; set; }
    }

    public partial class ClientInfo
    {
        [JsonProperty("button_actions")]
        public string[] ButtonActions { get; set; }

        [JsonProperty("keyboard")]
        public bool Keyboard { get; set; }

        [JsonProperty("inline_keyboard")]
        public bool InlineKeyboard { get; set; }

        [JsonProperty("carousel")]
        public bool Carousel { get; set; }

        [JsonProperty("lang_id")]
        public long LangId { get; set; }
    }

    public partial class Message
    {
        [JsonProperty("date")]
        public long Date { get; set; }

        [JsonProperty("from_id")]
        public long FromId { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("out")]
        public long Out { get; set; }

        [JsonProperty("attachments")]
        public MessageAttachment[] Attachments { get; set; }

        [JsonProperty("conversation_message_id")]
        public long ConversationMessageId { get; set; }

        [JsonProperty("fwd_messages")]
        public object[] FwdMessages { get; set; }

        [JsonProperty("important")]
        public bool Important { get; set; }

        [JsonProperty("is_hidden")]
        public bool IsHidden { get; set; }

        [JsonProperty("peer_id")]
        public long PeerId { get; set; }

        [JsonProperty("random_id")]
        public long RandomId { get; set; }

        [JsonProperty("ref")]
        public string Ref { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class MessageAttachment
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("wall")]
        public Wall Wall { get; set; }
        [JsonProperty("photo")]
        public Photo Photo {get;set;}
    }

    public partial class Wall
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("from_id")]
        public long FromId { get; set; }

        [JsonProperty("to_id")]
        public long ToId { get; set; }

        [JsonProperty("date")]
        public long Date { get; set; }

        [JsonProperty("donut")]
        public Donut Donut { get; set; }

        [JsonProperty("comments")]
        public Comments Comments { get; set; }

        [JsonProperty("marked_as_ads")]
        public long MarkedAsAds { get; set; }

        [JsonProperty("short_text_rate")]
        public double ShortTextRate { get; set; }

        [JsonProperty("compact_attachments_before_cut")]
        public long CompactAttachmentsBeforeCut { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("attachments")]
        public WallAttachment[] Attachments { get; set; }

        [JsonProperty("copyright")]
        public Copyright Copyright { get; set; }

        [JsonProperty("likes")]
        public Likes Likes { get; set; }

        [JsonProperty("owner_id")]
        public long OwnerId { get; set; }

        [JsonProperty("post_type")]
        public string PostType { get; set; }

        [JsonProperty("reposts")]
        public Comments Reposts { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("views")]
        public Comments Views { get; set; }

        [JsonProperty("from")]
        public From From { get; set; }
    }

    public partial class WallAttachment
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("photo")]
        public Photo Photo { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }
    }

    public partial class Photo
    {
        [JsonProperty("album_id")]
        public long AlbumId { get; set; }

        [JsonProperty("date")]
        public long Date { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("owner_id")]
        public long OwnerId { get; set; }

        [JsonProperty("access_key")]
        public string AccessKey { get; set; }

        [JsonProperty("post_id")]
        public long PostId { get; set; }

        [JsonProperty("sizes")]
        public Size[] Sizes { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("user_id")]
        public long UserId { get; set; }

        [JsonProperty("web_view_token")]
        public string WebViewToken { get; set; }

        [JsonProperty("has_tags")]
        public bool HasTags { get; set; }
    }

    public partial class Size
    {
        [JsonProperty("height")]
        public long Height { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }
    }

    public partial class Comments
    {
        [JsonProperty("count")]
        public long Count { get; set; }
    }

    public partial class Copyright
    {
        [JsonProperty("link")]
        public Uri Link { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class Donut
    {
        [JsonProperty("is_donut")]
        public bool IsDonut { get; set; }
    }

    public partial class From
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("screen_name")]
        public string ScreenName { get; set; }

        [JsonProperty("is_closed")]
        public long IsClosed { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("photo_50")]
        public Uri Photo50 { get; set; }

        [JsonProperty("photo_100")]
        public Uri Photo100 { get; set; }
    }

    public partial class Likes
    {
        [JsonProperty("can_like")]
        public long CanLike { get; set; }

        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("user_likes")]
        public long UserLikes { get; set; }
    }

    
}
