name: Build & Test

on:
  push:
  pull_request:

jobs:


  test:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Build
      run: dotnet test tests/Sunrise.Tests/Sunrise.Tests.csproj -c ${{ matrix.configuration }}

    - name: Upload Allure
      uses: actions/upload-artifact@v3
      with:
        name: allure-${{github.ref_name}}-${{github.sha}}-${{ matrix.configuration }}
        path: tests/Sunrise.Tests/bin/${{ matrix.configuration }}/net7.0/allure-results

  build:
    needs: test
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Build
      run: dotnet publish src/Sunrise/Sunrise.csproj -c ${{ matrix.configuration }} --force

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Binarys
        path: src/Sunrise/bin/${{ matrix.configuration }}/net7.0/publish # or path/to/artifact
  
  allure:
    needs: test
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: allure-${{github.ref_name}}-${{github.sha}}-${{ matrix.configuration }}
        path: allure-results


    - name: Get Allure Reports
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: allure-reports
        path: allure-reports

    
